language: python

python:
  - 3.8.5

install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - pipenv contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov